version: "3.2"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - ./app:/code
#    expose:
#      - "80"
    ports:
      - "8090:8090"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

#  letsencrypt:
#    build: ./letsencrypt
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./nginx/certs:/etc/nginx/certs
#    ports:
#      - "443:443"
#    depends_on:
#      - web
