version: "3.2"

services:
  db:
    image: postgres
#    command: postgresql-upgrade-database
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    command: python ./kpalch/manage.py makemigrations
    command: python manage.py migrate --run-syncdb
#    command: gunicorn taskmanager.wsgi:application -b 0.0.0.0:\$PORT
    volumes:
      - .:/code
    ports:
      - "80:80"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

