# Используем базовый образ Python
FROM python:3.9

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем requirements.txt в контейнер
COPY services/alice/requirements.txt .

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Копируем файлы сервиса Алисы
COPY services/alice/alice.py .

# Команда для запуска приложения Flask
CMD ["python", "alice.py"]
